version: '3'
services:
  jupyter:
    container_name: jupyter_container
    image: jupyter/minimal-notebook
    environment:
      - JUPYTER_TOKEN=root
    volumes:
      - ./data/jupyter:/home/jovyan/work
    ports:
      - 8888:8888
      - 8000:8000
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5159:5432"
    #volumes:
    #  - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
